apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # patch using Json6902
  # https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesjson6902/
  - target:
      kind: Service
    patch: |-
      - op: add
        path: /spec/ports/0/nodePort
        value: 30002
  - target:
      kind: Service
    path: service.yaml
