apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# 특정 리소스 삭제하기 (공식 문서엔 존재하지 않음)
# https://github.com/kubernetes-sigs/kustomize/issues/1593#issuecomment-944157718
patches:
- path: nginx-deployment-add-configmap.yaml
  target:
    kind: Deployment
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx
    $patch: delete
  target:
    kind: Service

# Generate ConfigMap from File
configMapGenerator:
- files:
  - nginx.conf
  name: nginx-config-from-file
- literals:
  - TEST_ENV=test string
  name: nginx-config-literal

images:
- name: nginx
  newTag: "1.23"
