apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: nginx-deployment-add-configmap.yaml
  target:
    kind: Deployment

# Generate ConfigMap from File
configMapGenerator:
- files:
  - nginx.conf
  name: nginx-config-from-file
- literals:
  - TEST_ENV=test string
  name: nginx-config-literal

images:
- name: nginx
  newTag: "1.23"
